name: environments
on:
  workflow_dispatch:

jobs:
  demo-environments:
    runs-on: macos-latest
    env:
      test_variable: ${{vars.VARIABLENAME}}
      token: ${{secrets.SECRETNAME}}
    
    steps:
      - run: echo $test_variable
      - run: echo $token